# Generated by Django 6.0 on 2026-03-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expense_amount_category_alter_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='note',
            new_name='description',
        ),
    ]
