# Generated by Django 6.0 on 2026-03-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_saving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyGroup',
        ),
    ]
